# Generated by Django 4.2.7 on 2025-09-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_address_cart_order_userprofile_paymentmethod_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, help_text="Order for display"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="store.address",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="card_number",
            field=models.CharField(
                blank=True, help_text="Encrypted card number", max_length=19
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="cardholder_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="productreview",
            name="helpful_votes",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of helpful votes"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                max_length=1,
            ),
        ),
    ]
